ARG UBUNTU_VERSION=16.04
FROM ubuntu:$UBUNTU_VERSION

# Install dependencies
RUN apt-get update \
  && apt-get install -y wget gcc make openssl libffi-dev libgdbm-dev libsqlite3-dev libssl-dev \
  zlib1g-dev git command-not-found less gzip vim x11-apps bzip2 libbz2-dev libfreetype6-dev \
  pkg-config libpng12-dev \
  && apt autoremove --yes \
  && apt-get clean

WORKDIR /tmp/


WORKDIR /app

COPY . .

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version

# ENTRYPOINT [ "python" ]
