name: CrystalPlan2
channels:
  - free
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.0
  - traitsui
  - mayavi
  - apptools
  - wxpython
  - matplotlib
  - vtk
  - scipy
  - gdk-pixbuf
  - atk-1.0
