name: CrystalPlan2
channels:
  - free
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - traitsui
  - mayavi
  - apptools
  - wxpython
  - numpy
  - matplotlib
  - vtk
  - scipy
  - gdk-pixbuf
  - atk-1.0
