name: CrystalPlan2
channels:
  - free
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - traitsui=5.0.0
  - mayavi=4.5.0
  - apptools=4.4.0
  - jsoncpp=0.10.6
  - wxpython=3.0.0
  - numpy=1.15.4
  - matplotlib=2.2.5
  - vtk
  - weave
  - scipy=1.2.3
  - gdk-pixbuf=2.42.10
  - atk-1.0
